[images]
  remote_images = [
    "https://same-assets.com/*"
  ]

[build]
  command = "bun run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

[dev]
  command = "bun run dev"
  port = 5173
  targetPort = 5173

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
