name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install  # Eğer React veya başka bir framework kullanıyorsan

      - name: Build Project
        run: npm run build  # React projeleri için genellikle bu kullanılır

      - name: Upload Artifact
        uses: actions/upload-artifact@v4  # ✅ Sürüm `v4` olarak güncellendi
        with:
          name: github-pages
          path: dist # Eğer React kullanıyorsan "build" klasörünü ayarla

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4  # ✅ Bu da en güncel sürüm
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist  # Eğer React kullanıyorsan "build" klasörünü ayarla
        

